// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/proto/primecruncher-v2.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileServerService_FetchSegment_FullMethodName = "/primecruncher_v2.FileServerService/FetchSegment"
)

// FileServerServiceClient is the client API for FileServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServerServiceClient interface {
	FetchSegment(ctx context.Context, in *FetchSegmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchSegmentResponse], error)
}

type fileServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServerServiceClient(cc grpc.ClientConnInterface) FileServerServiceClient {
	return &fileServerServiceClient{cc}
}

func (c *fileServerServiceClient) FetchSegment(ctx context.Context, in *FetchSegmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchSegmentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileServerService_ServiceDesc.Streams[0], FileServerService_FetchSegment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchSegmentRequest, FetchSegmentResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileServerService_FetchSegmentClient = grpc.ServerStreamingClient[FetchSegmentResponse]

// FileServerServiceServer is the server API for FileServerService service.
// All implementations must embed UnimplementedFileServerServiceServer
// for forward compatibility.
type FileServerServiceServer interface {
	FetchSegment(*FetchSegmentRequest, grpc.ServerStreamingServer[FetchSegmentResponse]) error
	mustEmbedUnimplementedFileServerServiceServer()
}

// UnimplementedFileServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServerServiceServer struct{}

func (UnimplementedFileServerServiceServer) FetchSegment(*FetchSegmentRequest, grpc.ServerStreamingServer[FetchSegmentResponse]) error {
	return status.Errorf(codes.Unimplemented, "method FetchSegment not implemented")
}
func (UnimplementedFileServerServiceServer) mustEmbedUnimplementedFileServerServiceServer() {}
func (UnimplementedFileServerServiceServer) testEmbeddedByValue()                           {}

// UnsafeFileServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServerServiceServer will
// result in compilation errors.
type UnsafeFileServerServiceServer interface {
	mustEmbedUnimplementedFileServerServiceServer()
}

func RegisterFileServerServiceServer(s grpc.ServiceRegistrar, srv FileServerServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileServerService_ServiceDesc, srv)
}

func _FileServerService_FetchSegment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchSegmentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileServerServiceServer).FetchSegment(m, &grpc.GenericServerStream[FetchSegmentRequest, FetchSegmentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileServerService_FetchSegmentServer = grpc.ServerStreamingServer[FetchSegmentResponse]

// FileServerService_ServiceDesc is the grpc.ServiceDesc for FileServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "primecruncher_v2.FileServerService",
	HandlerType: (*FileServerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchSegment",
			Handler:       _FileServerService_FetchSegment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/primecruncher-v2.proto",
}
