// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/primecruncher-v2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pathname      string                 `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Start         int64                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	ChunkSize     int64                  `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSegmentRequest) Reset() {
	*x = FetchSegmentRequest{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSegmentRequest) ProtoMessage() {}

func (x *FetchSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSegmentRequest.ProtoReflect.Descriptor instead.
func (*FetchSegmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{0}
}

func (x *FetchSegmentRequest) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (x *FetchSegmentRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *FetchSegmentRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FetchSegmentRequest) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type FetchSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSegmentResponse) Reset() {
	*x = FetchSegmentResponse{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSegmentResponse) ProtoMessage() {}

func (x *FetchSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSegmentResponse.ProtoReflect.Descriptor instead.
func (*FetchSegmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{1}
}

func (x *FetchSegmentResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_internal_proto_primecruncher_v2_proto protoreflect.FileDescriptor

const file_internal_proto_primecruncher_v2_proto_rawDesc = "" +
	"\n" +
	"%internal/proto/primecruncher-v2.proto\x12\x10primecruncher_v2\"~\n" +
	"\x13FetchSegmentRequest\x12\x1a\n" +
	"\bpathname\x18\x01 \x01(\tR\bpathname\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x04 \x01(\x03R\tchunkSize\",\n" +
	"\x14FetchSegmentResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2t\n" +
	"\x11FileServerService\x12_\n" +
	"\fFetchSegment\x12%.primecruncher_v2.FetchSegmentRequest\x1a&.primecruncher_v2.FetchSegmentResponse0\x01B\x12Z\x10./internal/protob\x06proto3"

var (
	file_internal_proto_primecruncher_v2_proto_rawDescOnce sync.Once
	file_internal_proto_primecruncher_v2_proto_rawDescData []byte
)

func file_internal_proto_primecruncher_v2_proto_rawDescGZIP() []byte {
	file_internal_proto_primecruncher_v2_proto_rawDescOnce.Do(func() {
		file_internal_proto_primecruncher_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_primecruncher_v2_proto_rawDesc), len(file_internal_proto_primecruncher_v2_proto_rawDesc)))
	})
	return file_internal_proto_primecruncher_v2_proto_rawDescData
}

var file_internal_proto_primecruncher_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_primecruncher_v2_proto_goTypes = []any{
	(*FetchSegmentRequest)(nil),  // 0: primecruncher_v2.FetchSegmentRequest
	(*FetchSegmentResponse)(nil), // 1: primecruncher_v2.FetchSegmentResponse
}
var file_internal_proto_primecruncher_v2_proto_depIdxs = []int32{
	0, // 0: primecruncher_v2.FileServerService.FetchSegment:input_type -> primecruncher_v2.FetchSegmentRequest
	1, // 1: primecruncher_v2.FileServerService.FetchSegment:output_type -> primecruncher_v2.FetchSegmentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_primecruncher_v2_proto_init() }
func file_internal_proto_primecruncher_v2_proto_init() {
	if File_internal_proto_primecruncher_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_primecruncher_v2_proto_rawDesc), len(file_internal_proto_primecruncher_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_primecruncher_v2_proto_goTypes,
		DependencyIndexes: file_internal_proto_primecruncher_v2_proto_depIdxs,
		MessageInfos:      file_internal_proto_primecruncher_v2_proto_msgTypes,
	}.Build()
	File_internal_proto_primecruncher_v2_proto = out.File
	file_internal_proto_primecruncher_v2_proto_goTypes = nil
	file_internal_proto_primecruncher_v2_proto_depIdxs = nil
}
