// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/primecruncher-v2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{0}
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pathname      string                 `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Start         int64                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"` // Indicates no more jobs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobResponse) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (x *GetJobResponse) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetJobResponse) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetJobResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type SubmitResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pathname      string                 `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Start         int64                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	PrimeCount    int64                  `protobuf:"varint,4,opt,name=prime_count,json=primeCount,proto3" json:"prime_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultRequest) Reset() {
	*x = SubmitResultRequest{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultRequest) ProtoMessage() {}

func (x *SubmitResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitResultRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitResultRequest) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (x *SubmitResultRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SubmitResultRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *SubmitResultRequest) GetPrimeCount() int64 {
	if x != nil {
		return x.PrimeCount
	}
	return 0
}

type SubmitResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultResponse) Reset() {
	*x = SubmitResultResponse{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultResponse) ProtoMessage() {}

func (x *SubmitResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitResultResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{3}
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{4}
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{5}
}

type DeregisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterWorkerRequest) Reset() {
	*x = DeregisterWorkerRequest{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterWorkerRequest) ProtoMessage() {}

func (x *DeregisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*DeregisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{6}
}

type DeregisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterWorkerResponse) Reset() {
	*x = DeregisterWorkerResponse{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterWorkerResponse) ProtoMessage() {}

func (x *DeregisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*DeregisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{7}
}

type FetchSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pathname      string                 `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Start         int64                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	ChunkSize     int64                  `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSegmentRequest) Reset() {
	*x = FetchSegmentRequest{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSegmentRequest) ProtoMessage() {}

func (x *FetchSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSegmentRequest.ProtoReflect.Descriptor instead.
func (*FetchSegmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{8}
}

func (x *FetchSegmentRequest) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (x *FetchSegmentRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *FetchSegmentRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FetchSegmentRequest) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type FetchSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSegmentResponse) Reset() {
	*x = FetchSegmentResponse{}
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSegmentResponse) ProtoMessage() {}

func (x *FetchSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_primecruncher_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSegmentResponse.ProtoReflect.Descriptor instead.
func (*FetchSegmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_primecruncher_v2_proto_rawDescGZIP(), []int{9}
}

func (x *FetchSegmentResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_internal_proto_primecruncher_v2_proto protoreflect.FileDescriptor

const file_internal_proto_primecruncher_v2_proto_rawDesc = "" +
	"\n" +
	"%internal/proto/primecruncher-v2.proto\x12\x10primecruncher_v2\"\x0f\n" +
	"\rGetJobRequest\"n\n" +
	"\x0eGetJobResponse\x12\x1a\n" +
	"\bpathname\x18\x01 \x01(\tR\bpathname\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\"\x80\x01\n" +
	"\x13SubmitResultRequest\x12\x1a\n" +
	"\bpathname\x18\x01 \x01(\tR\bpathname\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\x12\x1f\n" +
	"\vprime_count\x18\x04 \x01(\x03R\n" +
	"primeCount\"\x16\n" +
	"\x14SubmitResultResponse\"\x17\n" +
	"\x15RegisterWorkerRequest\"\x18\n" +
	"\x16RegisterWorkerResponse\"\x19\n" +
	"\x17DeregisterWorkerRequest\"\x1a\n" +
	"\x18DeregisterWorkerResponse\"~\n" +
	"\x13FetchSegmentRequest\x12\x1a\n" +
	"\bpathname\x18\x01 \x01(\tR\bpathname\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x04 \x01(\x03R\tchunkSize\",\n" +
	"\x14FetchSegmentResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2`\n" +
	"\x11DispatcherService\x12K\n" +
	"\x06GetJob\x12\x1f.primecruncher_v2.GetJobRequest\x1a .primecruncher_v2.GetJobResponse2\xc4\x02\n" +
	"\x13ConsolidatorService\x12]\n" +
	"\fSubmitResult\x12%.primecruncher_v2.SubmitResultRequest\x1a&.primecruncher_v2.SubmitResultResponse\x12c\n" +
	"\x0eRegisterWorker\x12'.primecruncher_v2.RegisterWorkerRequest\x1a(.primecruncher_v2.RegisterWorkerResponse\x12i\n" +
	"\x10DeregisterWorker\x12).primecruncher_v2.DeregisterWorkerRequest\x1a*.primecruncher_v2.DeregisterWorkerResponse2t\n" +
	"\x11FileServerService\x12_\n" +
	"\fFetchSegment\x12%.primecruncher_v2.FetchSegmentRequest\x1a&.primecruncher_v2.FetchSegmentResponse0\x01B\x12Z\x10./internal/protob\x06proto3"

var (
	file_internal_proto_primecruncher_v2_proto_rawDescOnce sync.Once
	file_internal_proto_primecruncher_v2_proto_rawDescData []byte
)

func file_internal_proto_primecruncher_v2_proto_rawDescGZIP() []byte {
	file_internal_proto_primecruncher_v2_proto_rawDescOnce.Do(func() {
		file_internal_proto_primecruncher_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_primecruncher_v2_proto_rawDesc), len(file_internal_proto_primecruncher_v2_proto_rawDesc)))
	})
	return file_internal_proto_primecruncher_v2_proto_rawDescData
}

var file_internal_proto_primecruncher_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_proto_primecruncher_v2_proto_goTypes = []any{
	(*GetJobRequest)(nil),            // 0: primecruncher_v2.GetJobRequest
	(*GetJobResponse)(nil),           // 1: primecruncher_v2.GetJobResponse
	(*SubmitResultRequest)(nil),      // 2: primecruncher_v2.SubmitResultRequest
	(*SubmitResultResponse)(nil),     // 3: primecruncher_v2.SubmitResultResponse
	(*RegisterWorkerRequest)(nil),    // 4: primecruncher_v2.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),   // 5: primecruncher_v2.RegisterWorkerResponse
	(*DeregisterWorkerRequest)(nil),  // 6: primecruncher_v2.DeregisterWorkerRequest
	(*DeregisterWorkerResponse)(nil), // 7: primecruncher_v2.DeregisterWorkerResponse
	(*FetchSegmentRequest)(nil),      // 8: primecruncher_v2.FetchSegmentRequest
	(*FetchSegmentResponse)(nil),     // 9: primecruncher_v2.FetchSegmentResponse
}
var file_internal_proto_primecruncher_v2_proto_depIdxs = []int32{
	0, // 0: primecruncher_v2.DispatcherService.GetJob:input_type -> primecruncher_v2.GetJobRequest
	2, // 1: primecruncher_v2.ConsolidatorService.SubmitResult:input_type -> primecruncher_v2.SubmitResultRequest
	4, // 2: primecruncher_v2.ConsolidatorService.RegisterWorker:input_type -> primecruncher_v2.RegisterWorkerRequest
	6, // 3: primecruncher_v2.ConsolidatorService.DeregisterWorker:input_type -> primecruncher_v2.DeregisterWorkerRequest
	8, // 4: primecruncher_v2.FileServerService.FetchSegment:input_type -> primecruncher_v2.FetchSegmentRequest
	1, // 5: primecruncher_v2.DispatcherService.GetJob:output_type -> primecruncher_v2.GetJobResponse
	3, // 6: primecruncher_v2.ConsolidatorService.SubmitResult:output_type -> primecruncher_v2.SubmitResultResponse
	5, // 7: primecruncher_v2.ConsolidatorService.RegisterWorker:output_type -> primecruncher_v2.RegisterWorkerResponse
	7, // 8: primecruncher_v2.ConsolidatorService.DeregisterWorker:output_type -> primecruncher_v2.DeregisterWorkerResponse
	9, // 9: primecruncher_v2.FileServerService.FetchSegment:output_type -> primecruncher_v2.FetchSegmentResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_primecruncher_v2_proto_init() }
func file_internal_proto_primecruncher_v2_proto_init() {
	if File_internal_proto_primecruncher_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_primecruncher_v2_proto_rawDesc), len(file_internal_proto_primecruncher_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_proto_primecruncher_v2_proto_goTypes,
		DependencyIndexes: file_internal_proto_primecruncher_v2_proto_depIdxs,
		MessageInfos:      file_internal_proto_primecruncher_v2_proto_msgTypes,
	}.Build()
	File_internal_proto_primecruncher_v2_proto = out.File
	file_internal_proto_primecruncher_v2_proto_goTypes = nil
	file_internal_proto_primecruncher_v2_proto_depIdxs = nil
}
